# Generated by Django 4.1.7 on 2024-04-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0008_jobapplication_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contactus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name="job",
            name="position",
            field=models.TextField(),
        ),
    ]
